services:
  app:
    build: .
    container_name: todo-app
    environment:
      - DATABASE_URL=postgresql://todoapp_db_bfu3_user:FwNPo4TNNW7dmFShGQDpaAu2dkDFF5kJ@dpg-d2csv4buibrs738rdg10-a.frankfurt-postgres.render.com/todoapp_db_bfu3
      - JWT_SECRET=wdawfga+24sa=fafvdfaWf2341541fq2br
      - NODE_ENV=development
      - PORT=5000
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate deploy && npx prisma generate && node ./src/server.js"
